version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  CSS_MODE: ${CSS_MODE-optimized}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: developer@endeavorb2b.com
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}
  DISABLE_IDX_NEWSLETTER_SIGNUP: ${DISABLE_IDX_NEWSLETTER_SIGNUP-true}
  NATIVEX_SERVE_URI: ${NATIVEX_SERVE_URI-}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  USE_LINK_INJECTED_BODY: ${USE_LINK_INJECTED_BODY-false}

x-env-tauron: &env-tauron
  <<: *env
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://tauron.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://tauron.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://tauron.sitemaps.base.parameter1.com}

x-env-development: &env-development
  <<: *env
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10102}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10202}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10302}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  id:
    <<: *site-cmd
    working_dir: /root/sites/inddist.com
    environment:
      <<: *env-tauron
      HOST: www-indm-id.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9710
      LIVERELOAD_PORT: 19710
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-id.dev.parameter1.com
    ports:
      - "9710:80"
      - "19710:19710"

  mnet:
    <<: *site-cmd
    working_dir: /root/sites/manufacturing.net
    environment:
      <<: *env-tauron
      HOST: www-indm-mnet.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9711
      LIVERELOAD_PORT: 19711
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-mnet.dev.parameter1.com
    ports:
      - "9711:80"
      - "19711:19711"

  fm:
    <<: *site-cmd
    working_dir: /root/sites/foodmanufacturing.com
    environment:
      <<: *env-tauron
      HOST: www-indm-fm.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9712
      LIVERELOAD_PORT: 19712
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-fm.dev.parameter1.com
    ports:
      - "9712:80"
      - "19712:19712"

  impo:
    <<: *site-cmd
    working_dir: /root/sites/impomag.com
    environment:
      <<: *env-tauron
      HOST: www-indm-impo.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9713
      LIVERELOAD_PORT: 19713
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-impo.dev.parameter1.com
    ports:
      - "9713:80"
      - "19713:19713"

  mbt:
    <<: *site-cmd
    working_dir: /root/sites/mbtmag.com
    environment:
      <<: *env-tauron
      HOST: www-indm-mbt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9714
      LIVERELOAD_PORT: 19714
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-mbt.dev.parameter1.com
    ports:
      - "9714:80"
      - "19714:19714"

  ien:
    <<: *site-cmd
    working_dir: /root/sites/ien.com
    environment:
      <<: *env-tauron
      HOST: www-indm-ien.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9715
      LIVERELOAD_PORT: 19715
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-ien.dev.parameter1.com
    ports:
      - "9715:80"
      - "19715:19715"

  cen:
    <<: *site-cmd
    working_dir: /root/sites/cannabisequipmentnews.com
    environment:
      <<: *env-tauron
      HOST: www-indm-cen.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9716
      LIVERELOAD_PORT: 19716
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-cen.dev.parameter1.com
    ports:
      - "9716:80"
      - "19716:19716"

  ddt:
    <<: *site-cmd
    working_dir: /root/sites/designdevelopmenttoday.com
    environment:
      <<: *env-tauron
      HOST: www-indm-ddt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9717
      LIVERELOAD_PORT: 19717
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-ddt.dev.parameter1.com
    ports:
      - "9717:80"
      - "19717:19717"

  mdd:
    <<: *site-cmd
    working_dir: /root/sites/medicaldesigndevelopment.com
    environment:
      <<: *env-tauron
      HOST: www-indm-mdd.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9718
      LIVERELOAD_PORT: 19718
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
    hostname: www-indm-mdd.dev.parameter1.com
    ports:
      - "9718:80"
      - "19718:19718"
