module.exports = {
  primary: {
    items: [
      { href: '/associations', label: 'Associations' },
      { href: '/awards', label: 'Awards' },
      // { href: '/big-50', label: 'Big 50' },
      { href: '/business-technology', label: 'Business Technology' },
      { href: '/company-expansion-consolidation', label: 'Company Exapansion & Consolidation' },
      { href: '/e-commerce', label: 'E-Commerce' },
      { href: '/earnings', label: 'Earnings' },
      { href: '/erp', label: 'ERP' },
      { href: '/economic-trends', label: 'Economic Trends' },
      { href: '/logistics', label: 'Logistics' },
      { href: '/mergers-acquisitions', label: 'Mergers & Acquisitions' },
      { href: '/operations', label: 'Operations' },
      { href: '/sales-management', label: 'Sales Management' },
      { href: '/staffing-changes', label: 'Staffing Changes' },
      { href: '/supply-chain', label: 'Supply Chain' },
      { href: '/technology-software', label: 'Technology & Software' },
      { href: '/workforce-development', label: 'Workforce Development' },
    ],
  },
  secondary: {
    items: [
      { href: '/page/about-us', label: 'About Us' },
      { href: '/page/advertising-info', label: 'Advertising Info' },
      { href: '/contact-us', label: 'Contact Us' },
      { href: '/page/directory-faqs', label: 'Directory FAQs' },
      { href: '/page/editorial-guidelines', label: 'Editorial Guidelines' },
      { href: '/page/privacy-policy', label: 'Privacy Policy' },
      { href: '/page/product-announcement-form', label: 'Product Announcement Form' },
      { href: '/subscribe', label: 'Subscriptions' },
      { href: '/page/terms-conditions', label: 'Terms & Conditions' },
      { href: '/magazine', label: 'Magazine' },
      { href: '/videos', label: 'Videos' },
      { href: '/white-papers', label: 'White Papers' },
      { href: '/events', label: 'Events' },
      { href: '/webinars', label: 'Webinars' },
    ],
  },
  tertiary: {
    items: [
      { href: '/search', label: 'Search', icon: 'search' },
    ],
  },
  footer: {
    items: [
      { href: '/page/about-us', label: 'About Us' },
      { href: '/page/advertising-info', label: 'Advertising Info' },
      { href: '/contact-us', label: 'Contact Us' },
      { href: '/page/privacy-policy', label: 'Privacy Policy' },
      { href: '/page/terms-conditions', label: 'Terms & Conditions' },
    ],
  },
  menu: [
    {
      label: 'Topics',
      items: [
        { href: '/associations', label: 'Associations' },
        { href: '/awards', label: 'Awards/Promotions' },
        // { href: '/big-50', label: 'Big 50' },
        { href: '/business-technology', label: 'Business Technology' },
        { href: '/earnings', label: 'Earnings' },
        { href: '/economic-trends', label: 'Economic Trends' },
        { href: '/logistics', label: 'Logistics' },
        { href: '/mergers-acquisitions', label: 'Mergers and Acquisitions' },
        { href: '/operations', label: 'Operations' },
        { href: '/sales-management', label: 'Sales Management' },
        { href: '/software', label: 'Software' },
        { href: '/supply-chain', label: 'Supply Chain' },
        { href: '/workforce-development', label: 'Workforce Development' },
      ],
    },
    {
      label: 'Resources',
      items: [
        { href: '/page/about-us', label: 'About Us' },
        { href: '/page/advertising-info', label: 'Advertising Info' },
        { href: '/contact-us', label: 'Contact Us' },
        { href: '/page/directory-faqs', label: 'Directory FAQs' },
        { href: '/page/editorial-guidelines', label: 'Editorial Guidelines' },
        { href: '/page/privacy-policy', label: 'Privacy Policy' },
        { href: '/page/product-announcement-form', label: 'Product Announcement Form' },
        { href: '/subscribe', label: 'Subscriptions' },
        { href: '/page/terms-conditions', label: 'Terms & Conditions' },
        { href: '/magazine', label: 'Magazine' },
        { href: '/videos', label: 'Videos' },
        { href: '/white-papers', label: 'White Papers' },
        { href: '/events', label: 'Events' },
      ],
    },
    {
      label: 'User Tools',
      items: [
        { href: '/subscribe', label: 'Subscribe' },
        { href: '/page/advertising-info', label: 'Advertising Info' },
        { href: '/page/about-us', label: 'About Us' },
        { href: '/contact-us', label: 'Contact Us' },
        { href: '/page/privacy-policy', label: 'Privacy Policy' },
      ],
    },
  ],
};
